### ISSUE TITLE
Device Option 

### ISSUE THREAD

**Issue by pmchaumien** [shaundon/lametric-spotify#1]
Hello Shaun

Thanks for your app, it’s great…
I managed to deploy it on heroku and it works great, I receive the information from my spotify account on my LAmetric... I'm over the moon....
But can you explain me how to include the option to know which device is used... I don't understand how to do it.
I don't know if it's in the index.js code or just in the Lametric application creator.
can you help me?

Thanks by advance

Pierre-Marie

**Comment by shaundon** [comment]
Hey, that's great to hear! 

On the Heroku side, the server is already set up to recognise `devices`, if you provide it, so you shouldn't need to edit the code at all. 

On the LaMetric app creator, add a text parameter to your app that corresponds to the `devices` parameter:

<img width="760" alt="Screen Shot 2021-02-16 at 08 52 18" src="https://user-images.githubusercontent.com/73652/108040266-fff83900-7034-11eb-89ad-0f9493febea6.png">

Then in the LaMetric app, you should see this parameter as a text field on the settings screen. You can set it here:

![IMG_B0A028E61F2C-1](https://user-images.githubusercontent.com/73652/108040377-2322e880-7035-11eb-847b-2c0f8dce7215.jpeg)

_(Note: It's called 'Speakers' for me as I gave the `devices` parameter a more user-friendly name)_

Then for that field, enter a comma-separated list of devices to match. So, if you only want your LaMetric to display songs playing on "Kitchen Echo" and "Living Room Echo", you'd enter `Kitchen Echo,Living Room Echo`.

Hope this helps!

**Comment by pmchaumien** [comment]
Thanks you, i will try 💯

**Comment by pmchaumien** [comment]
i made some code modification before your answer 

index.js 

        if (nowPlaying['is_playing'] && nowPlaying.item && nowPlaying.item.name && nowPlaying.item.artists) {
            const track = nowPlaying.item.name;
            const artists = nowPlaying.item.artists.map(artist => artist.name).join(', ');
            const device = nowPlaying.device.name;
            responseText = `${track} - ${artists}`;
            if (allowedDevices && !allowedDevices.includes(nowPlaying.device.name)) {
                responseText = `${track} - ${artists} - ${device}`;
            }
        }
        console.log(responseText);


and in the lametric app 
i put a checkbox with devices option but now 

![screencapture-developer-lametric-com-applications-app-25662-1613468894998 (1)](https://user-images.githubusercontent.com/12811096/108046619-1c03d680-7045-11eb-9b59-3c58d01487a4.png)

"lametric" show all the time the active device... even more when the checkbox is on false....

I'm a newbee with javascript and i'm little lost know...  in fact I want to be able to activate the option when I want to see the active device

**Comment by shaundon** [comment]
`devices` shouldn't be a checkbox, it should be a text field

**Comment by pmchaumien** [comment]
ok Shaun, i will try it 👍

**Comment by pmchaumien** [comment]
Thanks you Shaun, it's functional

**Comment by shaundon** [comment]
Ah that's great to hear, enjoy!
